### ISSUE TITLE
No Player Inventory sync

### ISSUE THREAD

**Issue by sakowskio** [Danielv123/playerManager#74]
Hello my Problem is simple it seems like i cant get this plugin working.

`ReferenceError: masterPlugins is not defined
    at /root/factorioClusterio/master.js:105:29
    at Layer.handle [as handle_request] (/root/factorioClusterio/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/root/factorioClusterio/node_modules/express/lib/router/index.js:317:13)
    at /root/factorioClusterio/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/root/factorioClusterio/node_modules/express/lib/router/index.js:335:12)
    at next (/root/factorioClusterio/node_modules/express/lib/router/index.js:275:10)
    at compression (/root/factorioClusterio/node_modules/compression/index.js:220:5)
    at Layer.handle [as handle_request] (/root/factorioClusterio/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/root/factorioClusterio/node_modules/express/lib/router/index.js:317:13)
    at /root/factorioClusterio/node_modules/express/lib/router/index.js:284:7
`

also my account is linkend on the Website and we have one mod extra "Space Exploration"

**Comment by Hornwitser** [comment]
This plugin is not maintained and doesn't work with Factorio 1.1. There are no plans to fix it.

**Comment by sakowskio** [comment]
Thanks for the help. Then I will try to rewrite it.

**Comment by Danielv123** [comment]
The update required is mostly just Hotpatch. We are considering doing 1.2.x to deprecated and making 2.0 the current version. It has an almost complete inventory sync with more features than this one.
